version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: microservices-frontend-dev
    restart: unless-stopped
    ports:
      - "${FRONTEND_DEV_PORT:-3001}:5173"
    networks:
      - frontend-network
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src:cached
      - ./public:/app/public:cached
      - ./index.html:/app/index.html:cached
      - ./vite.config.js:/app/vite.config.js:cached
      - ./package.json:/app/package.json:cached

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: microservices-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    networks:
      - frontend-network
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      timeout: 3s
      retries: 3
      interval: 30s
      start_period: 10s

networks:
  frontend-network:
    driver: bridge
    external: false